# 默认的profile为develop，其他环境通过指定启动参数使用不同的profile，比如：
#   开发环境：java -jar my-spring-boot.jar --spring.profiles.active=dev
#   测试环境：java -jar my-spring-boot.jar --spring.profiles.active=test
# springboot配置
spring:
    # 多环境配置
    profiles:
        active: dev