########################################################
### 开发环境配置
########################################################
# springboot配置
spring:
    # 多环境配置
    profiles: dev
    # Mysql DataSource
    datasource:
        # 主数据源，默认的
        main: master
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://192.168.30.26:3306/gd_dev?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=round&allowMultiQueries=true&autoReconnect=true
        #jdbc:mysql://127.0.0.1:3306/ji_db?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=round&allowMultiQueries=true&autoReconnect=true
        username: iperp_m2
        #root
        password: QbdxeI8MUyOsfcIv0xNNvGIC
        #123456
        driverClassName: com.mysql.jdbc.Driver
        # Keep the connection alive if idle for a long time (needed in production)
        testWhileIdle: true
        validationQuery: SELECT 1
        # 初始化大小，最小，最大
        initialSize: 5
        minIdle: 5
        maxActive: 20
        # 配置获取连接等待超时的时间
        maxWait: 60000
        #配置一个连接在池中最小生存的时间，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，‘wall‘用于防火墙
        filters: stat,wall,slf4j
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        # 合并多个DruidDataSource的监控数据
        useGlobalDataSourceStat: true
    mvc:
        view:
            prefix: /templates/
            suffix: .html

########################################################
### mybatis 配置
########################################################
mybatis:
      type-aliases-package: com.mc.ji.model
      mapper-locations: classpath*:mapper/*/*.xml

mapper:
      mappers: com.mc.ji.common.base.JiMapper
      not-empty: false
      identity: select uuid()
      order: before

pagehelper:
      helperDialect: mysql
      reasonable: true
      supportMethodsArguments: true
      params: count=countSql

########################################################
### server 配置
########################################################
server:
      port: 8088
      context-path: /

########################################################
### log 配置
########################################################
logging: # 与 logback.xml配置任选其一，如果两者存在，优先xml配置文件
      level:  #控制台输出——日志级别从低到高分为TRACE < DEBUG < INFO < WARN < ERROR < FATAL，如果设置为WARN，则低于WARN的信息都不会输出。
          root: info # logging.level.root=WARN：root日志以WARN级别输出
          tk.mybatis: info # logging.level.com.ji=DEBUG：com.ji包下所有class以DEBUG级别输出
      path: /log # 设置目录，会在该目录下创建spring.log文件，并写入日志内容
      #pattern:
          # file: %d{YYYY-MM-DD hh:mm:ss.SSS} [%thread] %-5level %logger{39} - %msg%n
          # file default ： （ %d{yyyy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } --- [%t] %-40.40logger{39} : %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx} ）
          # %d{HH: mm:ss.SSS}——日志输出时间 %thread——输出日志的进程名字，这在Web应用以及异步任务处理中很有用 %-5level——日志级别，并且使用5个字符靠左对齐 %logger{36}——日志输出者的名字 %msg——日志消息 %n——平台的换行符
          # console: %d{YYYY-MM-DD hh:mm:ss.SSS} [%thread] %-5level %logger{39} - %msg%n